### ISSUE TITLE
[Question] Diary model 및 호출 관련

### ISSUE THREAD

**Issue by markFT39** [Nein-to-Sick/bandi_official#11]
## 어떤 문제인가요?

> 현재 chatGPT 호출 관련한 코드 작성 중에 있는데, 유저의 입력(Diary)을 model로 따로 관리하는 것이 좋을 듯합니다.
> 제가 일기 작성 기능을 담당하지 않아서 해당 부분을 제가 어떻게 처리하면 좋을까요?

## 어떤 상황에서 발생한 문제인가요?

현재
> diary controller가 아직 없는 상황이기에 diray update 함수를 ai controller에서 일단 임의로 작성함
> diary controller에서 따로 관리하는 것은 어떨지

> diary model 역시 개발 상황에 따라 임의로 작성함
> 향후 개발에 있어 문제가 없도록 미리 확인 요망

## 참고할만한 자료(선택)

![image](https://github.com/user-attachments/assets/8883d6b4-ce74-4a53-9afb-65562e4f7c4d)
> 현재 ai controller에서 임의로 작성한 diary update 함수들.
> 이러한 함수는 diary controller에서 관리할 필요가 있어 보입니다.

![image](https://github.com/user-attachments/assets/e3ce61e2-2d76-471a-a9dd-d398af2f551e)
> diary model도 제가 개발 편의상 임의로 작성해 놓았으나, 향후 개발에 있어 충돌 등 문제가 있을 여지가 있어 확인이 필요합니다.

**Comment by KimGyeongLock** [comment]
반디가 건네는 한마디는 일회성이라면 빼도 되고
나의 일기를 찾을 때 공감 개수를 세어줄 필요가 있을 듯
<img width="263" alt="image" src="https://github.com/user-attachments/assets/bd9386ed-c19e-4014-a8bf-a421c3a59928">
\+ 이거는 고려해볼 사항인데
<img width="185" alt="image" src="https://github.com/user-attachments/assets/6b86069e-8d55-4609-b1e7-764e3fdee340"><br>
'공감한 일기'라는 것도 추가해야 될텐데 방법이 두가지 있음<br>
1) 공감한 일기와 내 일기를 model을 분리한다 -> 현재 내 일기로 되어 있는 Diary라는 이름이 모호하다.<br>
2) 공감한 일기, 내 일기 그냥 한 모델로 통일 -> 속성에 내가 쓴 일기임을 표시할 필요가 있음

**Comment by markFT39** [comment]
공감 개수는 일기 기록 개발 시에 반영하도록 하죠.

내가 공감한 일기 목록은 DB 수준에서 collection으로 분리될 테고, 내용은 내가 쓴 일기와 크게 다르지 않으니 model은 하나로 통일해도 무방할 것 같네요.

**Comment by KimGyeongLock** [comment]
좋습니다
