### ISSUE TITLE
[ISSUE] Navigation 배경 투명

### ISSUE THREAD

**Issue by KimGyeongLock** [Nein-to-Sick/bandi_official#13]
## 어떤 버그인가요?

> 네비게이션 넘겼을 때 다음 화면이 투명색으로 돼서 뒷 배경이 보여야 하는데 투명이 안됨 

## 어떤 상황에서 발생한 버그인가요?

> 아래 버튼 누르면 네비게이션 어두어짐 
> 파일은 view/home/write_diary.dart
<img width="51" alt="image" src="https://github.com/user-attachments/assets/89efb431-2636-4d11-b797-38dd182339be">

<img src="https://github.com/user-attachments/assets/bf1e77f1-ae25-484e-ad25-c6eec296c42a" width="300">

## 예상 결과

> 이걸 원함
<img src="https://github.com/user-attachments/assets/739bb2cb-d7ea-4998-817e-923b38cd7cd4" width="300">

**Comment by KimGyeongLock** [comment]
배터리 없어서 못하긴했지만 찾아주시면 감사..

**Comment by markFT39** [comment]
![image](https://github.com/user-attachments/assets/497396db-c3fa-4926-89cc-ab500b2884b0)

Widget Tree 구조를 보니, 배경은 Navigation Widget에서 그리는데, Navigator.push를 하면 이미지처럼 Material App 위에 쌓이네요. 이것 때문에 라우팅 후에 배경이 없는 것 같습니다.

저 역시 채팅 페이지 라우팅 후 provider 호출 시에  동일한 원인으로 provider가 widget tree의  조상 중에 없다는 오류를 발견했습니다. 배경 위치를 더 높은 widget에서 호출하거나, 배경을 한번 더 넣는 방법이 있을 듯하네요.
