### ISSUE TITLE
[ISSUE] background blur 수치

### ISSUE THREAD

**Issue by KimGyeongLock** [Nein-to-Sick/bandi_official#16]
## 어떤 버그인가요?

> 백그라운드가 피그마랑 약간 다름

## 어떤 상황에서 발생한 버그인가요?

> background blur가 16으로 되어있는데 소수가 되어야 함.

## 예상 결과

> 일단 16 / 100 으로 넣긴 했음

view/home/write_diary.dart
```
color: BandiColor.neutralColor10(context)
              .withOpacity(BandiEffects.backgroundBlur() / 100),
```

## 참고할만한 자료(선택)
<img width="200" alt="image" src="https://github.com/user-attachments/assets/96406fab-e78a-4fc2-a40a-fb1af08a8786">
<img width="180" alt="image" src="https://github.com/user-attachments/assets/9eaeaea5-0973-4e1b-b530-4050dd35a82e">
<br>
> 아 비슷한가...?

**Comment by KimGyeongLock** [comment]
약간 "기분이 어떠신가요?" 저거 멘트도 다르지 않음?

**Comment by markFT39** [comment]
![image](https://github.com/user-attachments/assets/c1d2ffd3-dcd8-4d1d-a5ab-52e918a7e287)

Figma에서 보면 사진과 같은 폰트 설정인 듯한데, 이거로 쓰신게 맞나요?

**Comment by markFT39** [comment]
![image](https://github.com/user-attachments/assets/52406b51-cd19-489f-839e-e090d95f02ed)
지금 개발 중인데 폰트 설정이 없는 경우가 있네요. 폰트 관련해서 디자이너에게 한 번 물어봐야 할듯하네요.
