### ISSUE TITLE
[BUG] theme figma, data 불일치

### ISSUE THREAD

**Issue by KimGyeongLock** [Nein-to-Sick/bandi_official#22]
## 어떤 버그인가요?

> figma에서 Typhography에 있는 font 정보가 불일치

## 어떤 상황에서 발생한 버그인가요?

[Body 3]
<img width="1070" alt="스크린샷 2024-07-30 오전 1 23 50" src="https://github.com/user-attachments/assets/de6fda89-04f6-48f6-9470-f35c5704fef8">    
글자 height = 22
<img width="458" alt="image" src="https://github.com/user-attachments/assets/843d0554-6a93-4fc0-97ec-c8ed04ad2b27">
글자 height = 16

\* small2 도 다른 거 확인

## 예상 결과

> 이 후 디자이너와 얘기를 해봐야 하겠지만 일단 Typhography에 있는 거 무시하고 일일이 확인하여 데이터 고쳐서 넣음
> **추후 모든 폰트 확인해볼 필요 있음**

**Comment by markFT39** [comment]
이번주 회의 때 이야기 해봅시다
