### ISSUE TITLE
[BUG] 일기 작성 textfield 버그

### ISSUE THREAD

**Issue by markFT39** [Nein-to-Sick/bandi_official#24]
## 어떤 버그인가요?

<img src="https://github.com/user-attachments/assets/cf006379-d33d-45a5-8cfe-161fdcdb5baf" alt="Navigation Bar" width="300"/>

> 실기기(모바일)에서 일기 작성 시에 한글이 나눠져 입력되는 버그가 있습니다.

## 어떤 상황에서 발생한 버그인가요?

<img src="https://github.com/user-attachments/assets/92298fdd-36aa-43a4-b0fd-4b36d6b95f87" alt="Navigation Bar" width="300"/>

> textfield의 onChanged에서 텍스트 값이 변할 때마다 setState를 호출해서 생기는 듯합니다.

**Comment by KimGyeongLock** [comment]
<img width="504" alt="image" src="https://github.com/user-attachments/assets/6e9870df-c1c5-4d70-baa8-a36eb1341e41">    

이런식으로 수정했으나 iOS에서는 처음부터 잘 작동되어서 확인할 방법이 없음
확인 바람

참고: <https://luvris2.tistory.com/804>

<img src="https://github.com/user-attachments/assets/e8de4ed2-b1ac-4be2-8f86-8f45a49db3d0" alt="Navigation Bar" width="300"/>

**Comment by KimGyeongLock** [comment]
아 setState 두 번 됐네... 나중에 다시 고침..
