### ISSUE TITLE
[BUG] phosphor icon 문제 있음

### ISSUE THREAD

**Issue by KimGyeongLock** [Nein-to-Sick/bandi_official#4]
## 어떤 버그인가요?

> phosphor_flutter 2.1.0 안에 fill 가득 채워진 아이콘이 없음,,

## 어떤 상황에서 발생한 버그인가요?

> figma에서 아이콘 뽑은게 phosphor 여기 껀데 pub_dev 에 있길래 다운받고 쓸려했는데 fill 아이콘이 없음

## 예상 결과

> 이미지 그냥 다운 받아야 할까요??

## 참고할만한 자료(선택)
pub.dev: <https://pub.dev/packages/phosphor_flutter/example>
<img width="442" alt="image" src="https://github.com/Nein-to-Sick/bandi_official/assets/63464299/0d3aa40a-ed80-488c-a93b-b5a5d24cf9fe">

**Comment by markFT39** [comment]
![image](https://github.com/Nein-to-Sick/bandi_official/assets/43339545/06b54730-7250-487c-87df-de1ca7b26ce5)
1.0.0 버전과 2.0.0 버전의 구문 변경이 있었던 걸로 보이는데 두 가지 모두 시도해보셨나요?

**Comment by KimGyeongLock** [comment]
<img width="337" alt="image" src="https://github.com/Nein-to-Sick/bandi_official/assets/63464299/71583c30-c4c5-4f9e-b1e2-574ca0f0ddb5"><br>
예시 자체가 안됨,,

**Comment by markFT39** [comment]
![image](https://github.com/Nein-to-Sick/bandi_official/assets/43339545/493fc5a2-c5f7-47ec-8aad-3b90b6bce7d2)

패키지의 코드를 보니까 style을 파라미터로 해서 직접 전달하면 되는 것 같네요
아래 코드로 작성해보니 적용되었습니다.

![image](https://github.com/Nein-to-Sick/bandi_official/assets/43339545/2f491a79-a0d6-42ef-8a18-128deb791170)

**Comment by KimGyeongLock** [comment]
나이스 굿
