### ISSUE TITLE
[BUG] 일기 작성시 기록 타이밍 문제

### ISSUE THREAD

**Issue by markFT39** [Nein-to-Sick/bandi_official#59]
## 어떤 버그인가요?

> 일기 작성 후 GPT 분석과 일기 저장 사이의 조작 문제

## 어떤 상황에서 발생한 버그인가요?

> 일기를 작성하고 GPT를 통해 제목, 감정, 응원의 한 마디 데이터를 얻어오기까지 시간이 걸립니다.
> 현재에선 데이터를 얻어오기 전까지 비어있는 화면을 그대로 보여줍니다.
> 데이터를 얻어오기전에 '확인'을 누르게되면 데이터가 초기화 되지 않은 상태로 DB에 저장됩니다.

## 가능한 해결책

> 데이터 분석이 완료되기전 단계를 추가할 필요가 있어 보입니다.

> 1. 반디 1.0 버전과 같이 분석 중에 로딩 화면을 노출 시키기
> 2. 데이터 분석 중에 '확인'버튼 비활성화
> 3. GPT 분석과 DB 저장을 Cloud function으로 구현하여 DB 수준에서 데이터 분석과 저장을 진행하기

> 유저의 사용성과 안정성을 고려하였을 때는 3번의 구현이 가장 좋아 보입니다만, 의견이 어떠신지 궁금합니다.
> 현재 파인 튜닝 진행한 GPT 모델의 답변 다양성과 성능을 개선하기 위해 작업 중에 있습니다. 관련해서 회의 때 논의 하면 좋을 듯합니다.

## 참고할만한 자료(선택)
<img src="https://github.com/user-attachments/assets/f2027a09-10e0-4fce-b5db-64bf14ebeaa7" width="300" alt="데이터 분석 중인 화면" />

**Comment by KimGyeongLock** [comment]
앱의 목적이 유저들의 감정 관리라면 결과를 확인할 필요가 있지 않을까,,

**Comment by markFT39** [comment]
키워드 분석 결과 확인 없이 넘어가면 기능의 의미가 퇴색 될 것 같기는 하네요.
일단 1번 혹은 2번을 우선 구현하면 좋을 것 같습니다.
