### ISSUE TITLE
[ISSUE] 폴더나 파일 naming

### ISSUE THREAD

**Issue by KimGyeongLock** [Nein-to-Sick/bandi_official#6]
버그는 아니고 폴더랑 파일 이름들이 뒤죽박죽이라   
카멜케이스 쓸건지, 스네이크 쓸건지 정하고
폴더랑 파일 네이밍도 짓기가 너무 어려워요...
<img width="254" alt="image" src="https://github.com/Nein-to-Sick/bandi_official/assets/63464299/35548c17-c53d-41ca-af08-67b9a6c42db6">

**Comment by markFT39** [comment]
mvc 패턴 기준으로 네이밍 규칙 정하면 좋을 것 같습니다.
1. 스네이크 케이스
2. model의 파일명은 단수형 명사
3. view & controller의 파일명은 기능 or 명사 + 접미사

예시
![image](https://github.com/user-attachments/assets/0a45851a-225d-46c8-9b31-c3fbdba4d975)
