### ISSUE TITLE
[BUG] 감정 없음 에러 처리

### ISSUE THREAD

**Issue by KimGyeongLock** [Nein-to-Sick/bandi_official#72]
## 어떤 버그인가요?

> 어떤 버그인지 간결하게 설명해주세요

페이지/위치: 작성된 일기 확인

<img src="https://github.com/user-attachments/assets/625f1596-c5db-406f-b203-0f0f48bffb53" width="200"/>

## 어떤 상황에서 발생한 버그인가요?

> (가능하면) Given-When-Then 형식으로 서술해주세요

- 설명: 반디가 분석한 감정이 없을시 대처 방법

**Comment by markFT39** [comment]
디자이너의 피드백 중 반디가 건네는 한마디에서 따옴표도 함께 제거하면 좋겠다고 합니다.

**Comment by KimGyeongLock** [comment]
감정이 없을 시 "없음"으로 대체
