### ISSUE TITLE
[BUG] 공감 일기 열람시 페이지가 닫히지 않는 문제

### ISSUE THREAD

**Issue by markFT39** [Nein-to-Sick/bandi_official#75]
## 어떤 버그인가요?

> 일기 작성 후 공감 표시를 하고 닫기 버튼을 눌렀을 때 페이지가 닫히지 않음

## 예상 결과

> DB 저장 코드 이후 네비게이터 변경 코드가 연달아 있을 때 연속적으로 동작하지 않을 가능성, 단 보관함 열람시 닫기 버튼을 누른 만큼 추가되어 있는 것으로 보아 다른 원인이 있을 것으로 보임

## 참고할만한 자료(선택)
<img src="https://github.com/user-attachments/assets/c5d53a6f-75c0-4215-92cf-3db729689c70" width="300"/>

**Comment by KimGyeongLock** [comment]
users 컬렉션에서 user Id 문서에 fcmToken 필드 값이 없어서 에러 발생
`[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: type 'Null' is not a subtype of type 'String'
`

**Comment by KimGyeongLock** [comment]
해결
