### ISSUE TITLE
[Question] Theme 색깔 문제

### ISSUE THREAD

**Issue by KimGyeongLock** [Nein-to-Sick/bandi_official#8]
## 어떤 버그인가요?

> Theme 현재 설정 어케 된건지 모르겠음

## 어떤 상황에서 발생한 버그인가요?

> 아래 black 80이나 white 60 설정이 되어 있는 지 모르겠음

## 참고할만한 자료(선택)
<img width="247" alt="image" src="https://github.com/user-attachments/assets/4cc4fdb5-2226-4600-beb2-cd67eb0767a9">

**Comment by markFT39** [comment]
현재 설정된 Theme은 이전 프로젝트의 파일을 옮겨온 것이구요. 현재 색상 설정은 반영되어 있지 않습니다.

**Comment by KimGyeongLock** [comment]
바꿔야 하는구만

**Comment by markFT39** [comment]
https://github.com/Nein-to-Sick/bandi_official/pull/10
ThemeData 수정하여서 PR 올렸습니다. 문제 없는지 확인 부탁드려요
