### ISSUE TITLE
[BUG] 계정 탈퇴시 편지함이 유지되는 버그

### ISSUE THREAD

**Issue by KimGyeongLock** [Nein-to-Sick/bandi_official#85]
## 어떤 버그인가요?

> 어떤 버그인지 간결하게 설명해주세요

계정 탈퇴시 편지함이 유지되는 버그

페이지/위치: 계정 탈퇴시

<img src="https://github.com/user-attachments/assets/5090f7b1-9281-44a2-b05b-496bbe46d946" width="200"/>

## 어떤 상황에서 발생한 버그인가요?

> (가능하면) Given-When-Then 형식으로 서술해주세요

- 문제 설명: firestore의 sub collection이 지워지지 않는 듯한 이슈

**Comment by markFT39** [comment]
로컬 저장소 데이터 삭제를 추가하려고 하는데 user_view와 auth_controller에 코드가 분산되어 있네요. 둘의 구분도 필요하지만 어느쪽이 계정 삭제 함수인지 구분이 안되어 추가하기 어렵네요.

일단 임시로 둘 다 추가해 놓았습니다. view와 controller 구분을 진행해주세요
